In [1]:
import numpy as np 

In [3]:
my_array = np.random.random([2,10])

In [4]:
my_array

array([[0.43248177, 0.5482987 , 0.96809611, 0.07878943, 0.2498502 ,
        0.10934106, 0.08891614, 0.47475664, 0.58437709, 0.42829675],
       [0.20439749, 0.43371395, 0.61100849, 0.06719501, 0.34587596,
        0.85505636, 0.29262728, 0.34253282, 0.9750701 , 0.13609515]])

In [5]:
my_array[0]

array([0.43248177, 0.5482987 , 0.96809611, 0.07878943, 0.2498502 ,
       0.10934106, 0.08891614, 0.47475664, 0.58437709, 0.42829675])

In [6]:
my_array[0][1]

0.5482987020278853

In [7]:
my_array[1][1]

0.4337139519310028

In [8]:
my_array[:3,1]

array([0.5482987 , 0.43371395])

In [9]:
my_array[:,1]

array([0.5482987 , 0.43371395])